# Generated by Django 4.0.6 on 2022-08-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('starting_bid', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('category', models.CharField(choices=[('NO', 'No category'), ('EL', 'Electronics'), ('TO', 'Toys'), ('HO', 'Home'), ('FA', 'Fashion'), ('SP', 'Sport')], default='NO', max_length=2)),
            ],
        ),
    ]
