# Generated by Django 4.0.6 on 2022-09-05 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.CreateModel(
            name='bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('bid_buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyerbid', to=settings.AUTH_USER_MODEL)),
                ('bid_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itembid', to='auctions.listing')),
            ],
        ),
    ]
